In [1]:
import cv2
import numpy as np
import pandas as pd

In [2]:
import os

In [3]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task")  # i need to change the directory where opencv_task folder present

In [4]:
os.getcwd()

'C:\\Users\\SSS\\Desktop\\opencv_task'

In [10]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\1")
img1=[]
for i in os.listdir():
    img1.append(cv2.imread((r"C:\Users\SSS\Desktop\opencv_task\1\{}").format(i),0).flatten())
    data_one=pd.DataFrame({'array':img1,'label':1})
img1

[array([161, 162, 163, ...,  17,  17,  17], dtype=uint8),
 array([161, 162, 163, ...,  17,  17,  17], dtype=uint8),
 array([161, 162, 163, ...,  17,  17,  17], dtype=uint8),
 array([160, 161, 161, ...,   8,   7,   7], dtype=uint8),
 array([160, 161, 161, ...,   8,   6,   7], dtype=uint8),
 array([160, 161, 161, ...,   8,   6,   7], dtype=uint8),
 array([162, 160, 160, ...,  13,  14,  16], dtype=uint8),
 array([162, 160, 160, ...,  13,  14,  16], dtype=uint8),
 array([162, 160, 160, ...,  13,  14,  16], dtype=uint8),
 array([162, 163, 163, ...,  15,  15,  16], dtype=uint8),
 array([164, 164, 164, ...,  15,  15,  16], dtype=uint8),
 array([164, 163, 161, ...,  13,  14,  15], dtype=uint8),
 array([164, 163, 161, ...,  13,  14,  15], dtype=uint8),
 array([164, 163, 161, ...,  13,  14,  15], dtype=uint8),
 array([164, 163, 161, ...,  13,  14,  15], dtype=uint8),
 array([165, 167, 168, ...,  22,  20,  19], dtype=uint8),
 array([167, 167, 166, ...,  22,  20,  19], dtype=uint8),
 array([167, 167, 166, ...,  22,  20,  19], dtype=uint8),
 array([162, 162, 162, ...,  23,  23,  25], dtype=uint8),
 array([162, 162, 162, ...,  23,  23,  25], dtype=uint8),
 array([161, 160, 159, ...,  26,  25,  25], dtype=uint8),
 array([161, 160, 159, ...,  26,  25,  25], dtype=uint8),
 array([163, 163, 162, ...,   4,   7,  10], dtype=uint8),
 array([163, 163, 162, ...,   4,   7,  10], dtype=uint8),
 array([163, 163, 163, ...,   6,  19,  21], dtype=uint8),
 array([163, 163, 163, ...,   6,  19,  21], dtype=uint8),
 array([163, 163, 163, ...,   6,  19,  21], dtype=uint8),
 array([163, 164, 164, ...,  20,  24,  23], dtype=uint8),
 array([163, 164, 164, ...,  20,  24,  23], dtype=uint8),
 array([163, 164, 164, ...,  20,  24,  23], dtype=uint8),
 array([160, 160, 160, ...,  24,  25,  26], dtype=uint8),
 array([160, 160, 160, ...,  24,  25,  26], dtype=uint8),
 array([160, 160, 160, ...,  24,  25,  26], dtype=uint8),
 array([161, 161, 161, ...,  29,  28,  30], dtype=uint8),
 array([161, 161, 161, ...,  29,  28,  30], dtype=uint8),
 array([166, 166, 165, ...,  27,  24,  26], dtype=uint8),
 array([166, 166, 165, ...,  27,  24,  26], dtype=uint8),
 array([166, 166, 165, ...,  27,  24,  26], dtype=uint8),
 array([163, 163, 163, ...,  29,  27,  28], dtype=uint8),
 array([163, 163, 163, ...,  29,  27,  28], dtype=uint8),
 array([163, 163, 163, ...,  29,  27,  28], dtype=uint8),
 array([163, 163, 163, ...,  29,  27,  28], dtype=uint8),
 array([162, 161, 160, ...,  29,  28,  27], dtype=uint8),
 array([162, 161, 160, ...,  29,  28,  27], dtype=uint8),
 array([163, 162, 162, ...,  26,  27,  29], dtype=uint8),
 array([163, 162, 162, ...,  26,  27,  29], dtype=uint8),
 array([163, 162, 162, ...,  26,  27,  29], dtype=uint8),
 array([161, 161, 161, ...,  23,  23,  22], dtype=uint8),
 array([161, 161, 161, ...,  23,  23,  22], dtype=uint8),
 array([161, 161, 161, ...,  23,  23,  22], dtype=uint8),
 array([162, 162, 162, ...,  25,  30,  26], dtype=uint8),
 array([162, 162, 162, ...,  25,  30,  26], dtype=uint8),
 array([162, 162, 162, ...,  25,  30,  26], dtype=uint8),
 array([163, 162, 161, ...,  26,  24,  24], dtype=uint8),
 array([163, 162, 161, ...,  26,  24,  24], dtype=uint8),
 array([163, 162, 161, ...,  26,  24,  24], dtype=uint8),
 array([161, 161, 161, ...,  25,  24,  21], dtype=uint8),
 array([161, 161, 161, ...,  25,  24,  21], dtype=uint8),
 array([161, 161, 161, ...,  25,  24,  21], dtype=uint8),
 array([160, 161, 160, ...,  27,  24,  24], dtype=uint8),
 array([160, 161, 160, ...,  27,  24,  24], dtype=uint8),
 array([160, 161, 160, ...,  27,  24,  24], dtype=uint8),
 array([166, 165, 164, ...,  30,  30,  29], dtype=uint8),
 array([166, 165, 164, ...,  30,  30,  29], dtype=uint8),
 array([166, 165, 164, ...,  30,  30,  29], dtype=uint8),
 array([163, 162, 160, ...,  21,  21,  21], dtype=uint8),
 array([163, 162, 160, ...,  21,  21,  21], dtype=uint8),
 array([163, 162, 160, ...,  21,  21,  21], dtype=uint8),
 array([164, 163, 160, ...,  20,  20,  21], dtype=uint8),
 array([164, 163, 160, ...,  20,  20,  21], dtype=uint8),
 array([161, 162, 163, ...,  24,  24,  24], dtype=uint8),
 array([161, 162, 163, ...,  24,  24,  24], dtype=uint8),
 array([161, 162, 163, ...,  24,  24,  24], dtype=uint8),
 array([159, 158, 157, ...,  23,  25,  26], dtype=uint8),
 array([159, 158, 157, ...,  23,  25,  26], dtype=uint8),
 array([159, 158, 157, ...,  23,  25,  26], dtype=uint8),
 array([161, 161, 161, ...,  26,  26,  25], dtype=uint8),
 array([161, 161, 161, ...,  26,  26,  25], dtype=uint8),
 array([161, 161, 161, ...,  26,  26,  25], dtype=uint8),
 array([161, 160, 159, ...,  24,  25,  27], dtype=uint8),
 array([161, 160, 159, ...,  24,  25,  27], dtype=uint8),
 array([161, 160, 159, ...,  24,  25,  27], dtype=uint8),
 array([164, 165, 165, ...,  25,  27,  29], dtype=uint8),
 array([164, 165, 165, ...,  25,  27,  29], dtype=uint8),
 array([164, 165, 165, ...,  25,  27,  29], dtype=uint8),
 array([161, 161, 161, ...,  21,  24,  25], dtype=uint8),
 array([161, 161, 161, ...,  21,  24,  25], dtype=uint8),
 array([161, 161, 161, ...,  21,  24,  25], dtype=uint8),
 array([159, 159, 160, ...,  28,  29,  29], dtype=uint8),
 array([159, 159, 160, ...,  28,  29,  29], dtype=uint8),
 array([159, 159, 160, ...,  28,  29,  29], dtype=uint8),
 array([161, 162, 162, ...,  22,  22,  22], dtype=uint8),
 array([161, 162, 162, ...,  22,  22,  22], dtype=uint8),
 array([161, 162, 162, ...,  22,  22,  22], dtype=uint8),
 array([162, 161, 161, ...,  29,  31,  31], dtype=uint8),
 array([162, 161, 161, ...,  29,  31,  31], dtype=uint8),
 array([162, 161, 161, ...,  29,  31,  31], dtype=uint8),
 array([163, 163, 162, ...,  22,  22,  23], dtype=uint8),
 array([163, 163, 162, ...,  22,  22,  23], dtype=uint8),
 array([163, 163, 162, ...,  22,  22,  23], dtype=uint8),
 array([162, 161, 160, ...,  25,  25,  24], dtype=uint8),
 array([162, 161, 160, ...,  25,  25,  24], dtype=uint8),
 array([162, 161, 160, ...,  25,  25,  24], dtype=uint8),
 array([161, 161, 161, ...,  24,  25,  26], dtype=uint8),
 array([161, 161, 161, ...,  24,  25,  26], dtype=uint8),
 array([163, 162, 161, ...,  26,  29,  26], dtype=uint8),
 array([163, 162, 161, ...,  26,  29,  26], dtype=uint8),
 array([163, 162, 161, ...,  26,  29,  26], dtype=uint8),
 array([161, 160, 158, ...,  24,  22,  21], dtype=uint8),
 array([161, 160, 158, ...,  24,  22,  21], dtype=uint8),
 array([161, 160, 158, ...,  24,  22,  21], dtype=uint8),
 array([163, 163, 162, ...,  21,  22,  22], dtype=uint8),
 array([163, 163, 162, ...,  21,  22,  22], dtype=uint8),
 array([163, 163, 162, ...,  21,  22,  22], dtype=uint8),
 array([158, 158, 158, ...,  28,  29,  28], dtype=uint8),
 array([158, 158, 158, ...,  28,  29,  28], dtype=uint8),
 array([158, 158, 158, ...,  28,  29,  28], dtype=uint8),
 array([160, 157, 155, ...,  26,  26,  25], dtype=uint8),
 array([160, 157, 155, ...,  26,  26,  25], dtype=uint8),
 array([160, 157, 155, ...,  26,  26,  25], dtype=uint8),
 array([160, 159, 159, ...,  24,  24,  24], dtype=uint8),
 array([160, 159, 159, ...,  24,  24,  24], dtype=uint8),
 array([160, 159, 159, ...,  24,  24,  24], dtype=uint8),
 array([160, 160, 159, ...,  25,  25,  24], dtype=uint8),
 array([160, 160, 159, ...,  25,  25,  24], dtype=uint8),
 array([160, 160, 159, ...,  25,  25,  24], dtype=uint8),
 array([161, 161, 160, ...,  23,  22,  22], dtype=uint8),
 array([161, 161, 160, ...,  23,  22,  22], dtype=uint8),
 array([161, 161, 160, ...,  23,  22,  22], dtype=uint8),
 array([164, 162, 160, ...,  23,  23,  22], dtype=uint8),
 array([164, 162, 160, ...,  23,  23,  22], dtype=uint8),
 array([164, 162, 160, ...,  23,  23,  22], dtype=uint8),
 array([162, 161, 159, ...,  21,  23,  24], dtype=uint8),
 array([162, 161, 159, ...,  21,  23,  24], dtype=uint8),
 array([160, 161, 161, ...,  23,  18,  19], dtype=uint8),
 array([160, 161, 161, ...,  23,  18,  19], dtype=uint8),
 array([160, 161, 161, ...,  23,  18,  19], dtype=uint8),
 array([160, 161, 161, ...,  23,  18,  19], dtype=uint8),
 array([158, 158, 157, ...,  28,  19,  17], dtype=uint8),
 array([158, 158, 157, ...,  28,  19,  17], dtype=uint8),
 array([158, 158, 158, ...,  18,  15,  14], dtype=uint8),
 array([158, 158, 158, ...,  18,  15,  14], dtype=uint8),
 array([158, 158, 158, ...,  18,  15,  14], dtype=uint8),
 array([161, 160, 159, ...,  21,  14,   7], dtype=uint8),
 array([161, 160, 159, ...,  21,  14,   7], dtype=uint8),
 array([161, 160, 159, ...,  21,  14,   7], dtype=uint8),
 array([160, 159, 159, ...,  21,  13,   9], dtype=uint8),
 array([160, 159, 159, ...,  21,  13,   9], dtype=uint8),
 array([160, 159, 159, ...,  21,  13,   9], dtype=uint8),
 array([158, 158, 158, ...,  23,  14,  10], dtype=uint8),
 array([158, 158, 158, ...,  23,  14,  10], dtype=uint8),
 array([158, 158, 158, ...,  23,  14,  10], dtype=uint8),
 array([159, 159, 158, ...,  24,  14,   9], dtype=uint8),
 array([159, 159, 158, ...,  24,  14,   9], dtype=uint8),
 array([159, 159, 158, ...,  24,  14,   9], dtype=uint8),
 array([159, 159, 159, ...,  18,   9,   9], dtype=uint8)]

In [11]:
data_one

                                                 array  label
0    [161, 162, 163, 164, 164, 163, 161, 159, 159, ...      1
1    [161, 162, 163, 164, 164, 163, 161, 159, 159, ...      1
2    [161, 162, 163, 164, 164, 163, 161, 159, 159, ...      1
3    [160, 161, 161, 161, 160, 159, 159, 158, 159, ...      1
4    [160, 161, 161, 162, 161, 160, 159, 159, 160, ...      1
..                                                 ...    ...
151  [158, 158, 158, 158, 159, 159, 158, 156, 152, ...      1
152  [159, 159, 158, 158, 158, 157, 156, 155, 155, ...      1
153  [159, 159, 158, 158, 158, 157, 156, 155, 155, ...      1
154  [159, 159, 158, 158, 158, 157, 156, 155, 155, ...      1
155  [159, 159, 159, 158, 158, 158, 158, 158, 158, ...      1

[156 rows x 2 columns]

In [12]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\2")
img2=[]
for i in os.listdir():
    img2.append(cv2.imread(r"C:\Users\SSS\Desktop\opencv_task\2\{}".format(i),0).flatten())
    data_two=pd.DataFrame({'array':img2,'label':2})
img2

[array([199, 199, 196, ...,   1,   0,   0], dtype=uint8),
 array([199, 199, 196, ...,   1,   0,   0], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([194, 193, 192, ...,   0,   0,   0], dtype=uint8),
 array([194, 193, 192, ...,   0,   0,   0], dtype=uint8),
 array([194, 193, 192, ...,   0,   0,   0], dtype=uint8),
 array([199, 198, 196, ...,   0,   0,   0], dtype=uint8),
 array([199, 198, 196, ...,   0,   0,   0], dtype=uint8),
 array([199, 198, 196, ...,   0,   0,   0], dtype=uint8),
 array([200, 199, 197, ...,   0,   0,   0], dtype=uint8),
 array([200, 199, 197, ...,   0,   0,   0], dtype=uint8),
 array([200, 199, 197, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 196, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 196, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 196, ...,   0,   0,   0], dtype=uint8),
 array([198, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([198, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([201, 199, 196, ...,   1,   1,   1], dtype=uint8),
 array([201, 199, 196, ...,   1,   1,   1], dtype=uint8),
 array([201, 199, 196, ...,   1,   1,   1], dtype=uint8),
 array([200, 201, 200, ...,   0,   0,   0], dtype=uint8),
 array([200, 201, 200, ...,   0,   0,   0], dtype=uint8),
 array([200, 201, 200, ...,   0,   0,   0], dtype=uint8),
 array([202, 201, 200, ...,   0,   0,   0], dtype=uint8),
 array([202, 201, 200, ...,   0,   0,   0], dtype=uint8),
 array([202, 201, 200, ...,   0,   0,   0], dtype=uint8),
 array([200, 200, 198, ...,   0,   0,   1], dtype=uint8),
 array([200, 200, 198, ...,   0,   0,   1], dtype=uint8),
 array([200, 200, 198, ...,   0,   0,   1], dtype=uint8),
 array([201, 200, 198, ...,  19,  18,  18], dtype=uint8),
 array([201, 200, 198, ...,  19,  18,  18], dtype=uint8),
 array([201, 200, 198, ...,  19,  18,  18], dtype=uint8),
 array([201, 200, 198, ...,  17,  20,  22], dtype=uint8),
 array([201, 200, 198, ...,  17,  20,  22], dtype=uint8),
 array([201, 200, 198, ...,  17,  20,  22], dtype=uint8),
 array([199, 199, 198, ...,  10,  11,  12], dtype=uint8),
 array([199, 199, 198, ...,  10,  11,  12], dtype=uint8),
 array([199, 199, 198, ...,  10,  11,  12], dtype=uint8),
 array([200, 199, 198, ...,  13,  14,  15], dtype=uint8),
 array([200, 199, 198, ...,  13,  14,  15], dtype=uint8),
 array([200, 199, 198, ...,  13,  14,  15], dtype=uint8),
 array([200, 198, 197, ...,  11,  10,  12], dtype=uint8),
 array([200, 198, 197, ...,  11,  10,  12], dtype=uint8),
 array([200, 198, 197, ...,  11,  10,  12], dtype=uint8),
 array([201, 201, 200, ...,  14,  12,  10], dtype=uint8),
 array([201, 201, 200, ...,  14,  12,  10], dtype=uint8),
 array([201, 201, 200, ...,  14,  12,  10], dtype=uint8),
 array([200, 199, 197, ...,  16,  16,  16], dtype=uint8),
 array([200, 199, 197, ...,  16,  16,  16], dtype=uint8),
 array([200, 199, 197, ...,  16,  16,  16], dtype=uint8),
 array([200, 200, 200, ...,  18,  19,  19], dtype=uint8),
 array([200, 200, 200, ...,  18,  19,  19], dtype=uint8),
 array([199, 198, 197, ...,  13,  11,  11], dtype=uint8),
 array([199, 198, 197, ...,  13,  11,  11], dtype=uint8),
 array([199, 198, 197, ...,  13,  11,  11], dtype=uint8),
 array([200, 199, 197, ...,  17,  16,  22], dtype=uint8),
 array([200, 199, 197, ...,  17,  16,  22], dtype=uint8),
 array([200, 199, 197, ...,  17,  16,  22], dtype=uint8),
 array([201, 199, 196, ...,  19,  18,  16], dtype=uint8),
 array([201, 199, 196, ...,  19,  18,  16], dtype=uint8),
 array([201, 199, 196, ...,  19,  18,  16], dtype=uint8),
 array([199, 199, 197, ...,  18,  16,  14], dtype=uint8),
 array([199, 199, 197, ...,  18,  16,  14], dtype=uint8),
 array([199, 199, 197, ...,  18,  16,  14], dtype=uint8),
 array([201, 200, 199, ...,  19,  18,  18], dtype=uint8),
 array([201, 200, 199, ...,  19,  18,  18], dtype=uint8),
 array([201, 200, 199, ...,  19,  18,  18], dtype=uint8),
 array([200, 199, 197, ...,  13,  11,  10], dtype=uint8),
 array([200, 199, 197, ...,  13,  11,  10], dtype=uint8),
 array([200, 199, 197, ...,  13,  11,  10], dtype=uint8),
 array([200, 199, 198, ...,  15,  15,  16], dtype=uint8),
 array([200, 199, 198, ...,  15,  15,  16], dtype=uint8),
 array([200, 199, 198, ...,  15,  15,  16], dtype=uint8),
 array([199, 199, 199, ...,  14,  14,  15], dtype=uint8),
 array([199, 199, 199, ...,  14,  14,  15], dtype=uint8),
 array([199, 199, 199, ...,  14,  14,  15], dtype=uint8),
 array([198, 199, 198, ...,   9,   9,  11], dtype=uint8)]

In [13]:
data_two

                                                array  label
0   [199, 199, 196, 194, 193, 192, 191, 190, 188, ...      2
1   [199, 199, 196, 194, 193, 192, 191, 190, 188, ...      2
2   [195, 195, 194, 192, 190, 189, 189, 189, 187, ...      2
3   [195, 195, 194, 192, 190, 189, 189, 189, 187, ...      2
4   [195, 195, 194, 192, 190, 189, 189, 189, 187, ...      2
..                                                ...    ...
77  [200, 199, 198, 197, 195, 194, 193, 191, 191, ...      2
78  [199, 199, 199, 198, 197, 196, 194, 193, 193, ...      2
79  [199, 199, 199, 198, 197, 196, 194, 193, 193, ...      2
80  [199, 199, 199, 198, 197, 196, 194, 193, 193, ...      2
81  [198, 199, 198, 197, 196, 195, 193, 191, 192, ...      2

[82 rows x 2 columns]

In [14]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\3")
img3=[]
for i in os.listdir():
    img3.append(cv2.imread(r"C:\Users\SSS\Desktop\opencv_task\3\{}".format(i),0).flatten())
    data_three=pd.DataFrame({'array':img3,'label':3})
img3

[array([199, 199, 198, ...,   1,   0,   0], dtype=uint8),
 array([199, 199, 198, ...,   1,   0,   0], dtype=uint8),
 array([200, 199, 197, ...,   0,   0,   0], dtype=uint8),
 array([200, 199, 197, ...,   0,   0,   0], dtype=uint8),
 array([200, 199, 197, ...,   0,   0,   0], dtype=uint8),
 array([198, 198, 198, ...,   0,   0,   0], dtype=uint8),
 array([198, 198, 198, ...,   0,   0,   0], dtype=uint8),
 array([198, 198, 198, ...,   0,   0,   0], dtype=uint8),
 array([198, 197, 196, ...,   0,   0,   0], dtype=uint8),
 array([198, 197, 196, ...,   0,   0,   0], dtype=uint8),
 array([198, 197, 196, ...,   0,   0,   0], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([198, 198, 197, ...,   0,   0,   0], dtype=uint8),
 array([198, 198, 197, ...,   0,   0,   0], dtype=uint8),
 array([198, 198, 197, ...,   0,   0,   0], dtype=uint8),
 array([197, 195, 193, ...,   0,   0,   0], dtype=uint8),
 array([197, 195, 193, ...,   0,   0,   0], dtype=uint8),
 array([197, 195, 193, ...,   0,   0,   0], dtype=uint8),
 array([195, 193, 191, ...,   0,   0,   0], dtype=uint8),
 array([195, 193, 191, ...,   0,   0,   0], dtype=uint8),
 array([195, 193, 191, ...,   0,   0,   0], dtype=uint8),
 array([195, 194, 192, ...,   0,   0,   0], dtype=uint8),
 array([195, 194, 192, ...,   0,   0,   0], dtype=uint8),
 array([198, 195, 193, ...,   0,   0,   0], dtype=uint8),
 array([198, 195, 193, ...,   0,   0,   0], dtype=uint8),
 array([198, 195, 193, ...,   0,   0,   0], dtype=uint8),
 array([193, 191, 189, ...,   0,   0,   0], dtype=uint8),
 array([193, 191, 189, ...,   0,   0,   0], dtype=uint8),
 array([138, 138, 138, ...,   0,   0,   0], dtype=uint8),
 array([137, 136, 135, ...,   0,   0,   0], dtype=uint8),
 array([137, 136, 135, ...,   0,   0,   0], dtype=uint8),
 array([137, 136, 135, ...,   0,   0,   0], dtype=uint8),
 array([146, 143, 140, ...,   0,   0,   0], dtype=uint8),
 array([68, 66, 60, ...,  0,  0,  0], dtype=uint8),
 array([68, 66, 60, ...,  0,  0,  0], dtype=uint8),
 array([68, 66, 60, ...,  0,  0,  0], dtype=uint8),
 array([53, 51, 49, ...,  0,  0,  0], dtype=uint8),
 array([53, 51, 49, ...,  0,  0,  0], dtype=uint8),
 array([53, 51, 49, ...,  0,  0,  0], dtype=uint8),
 array([51, 52, 49, ...,  0,  0,  0], dtype=uint8),
 array([80, 80, 80, ...,  0,  0,  0], dtype=uint8),
 array([80, 80, 80, ...,  0,  0,  0], dtype=uint8),
 array([80, 80, 80, ...,  0,  0,  0], dtype=uint8)]

In [15]:
data_three

                                                array  label
0   [199, 199, 198, 197, 196, 194, 192, 191, 192, ...      3
1   [199, 199, 198, 197, 196, 194, 192, 191, 192, ...      3
2   [200, 199, 197, 196, 195, 194, 192, 190, 188, ...      3
3   [200, 199, 197, 196, 195, 194, 192, 190, 188, ...      3
4   [200, 199, 197, 196, 195, 194, 192, 190, 188, ...      3
5   [198, 198, 198, 196, 193, 190, 189, 188, 187, ...      3
6   [198, 198, 198, 196, 193, 190, 189, 188, 187, ...      3
7   [198, 198, 198, 196, 193, 190, 189, 188, 187, ...      3
8   [198, 197, 196, 195, 193, 192, 192, 192, 188, ...      3
9   [198, 197, 196, 195, 193, 192, 192, 192, 188, ...      3
10  [198, 197, 196, 195, 193, 192, 192, 192, 188, ...      3
11  [195, 195, 194, 193, 192, 191, 189, 187, 185, ...      3
12  [195, 195, 194, 193, 192, 191, 189, 187, 185, ...      3
13  [195, 195, 194, 193, 192, 191, 189, 187, 185, ...      3
14  [198, 198, 197, 195, 194, 193, 189, 187, 185, ...      3
15  [198, 198, 197, 195, 194, 193, 189, 187, 185, ...      3
16  [198, 198, 197, 195, 194, 193, 189, 187, 185, ...      3
17  [197, 195, 193, 191, 190, 190, 190, 189, 189, ...      3
18  [197, 195, 193, 191, 190, 190, 190, 189, 189, ...      3
19  [197, 195, 193, 191, 190, 190, 190, 189, 189, ...      3
20  [195, 193, 191, 190, 189, 188, 186, 184, 184, ...      3
21  [195, 193, 191, 190, 189, 188, 186, 184, 184, ...      3
22  [195, 193, 191, 190, 189, 188, 186, 184, 184, ...      3
23  [195, 194, 192, 191, 190, 188, 186, 185, 182, ...      3
24  [195, 194, 192, 191, 190, 188, 186, 185, 182, ...      3
25  [198, 195, 193, 192, 191, 190, 188, 187, 184, ...      3
26  [198, 195, 193, 192, 191, 190, 188, 187, 184, ...      3
27  [198, 195, 193, 192, 191, 190, 188, 187, 184, ...      3
28  [193, 191, 189, 188, 188, 188, 186, 185, 183, ...      3
29  [193, 191, 189, 188, 188, 188, 186, 185, 183, ...      3
30  [138, 138, 138, 137, 135, 133, 132, 132, 131, ...      3
31  [137, 136, 135, 135, 134, 133, 132, 132, 131, ...      3
32  [137, 136, 135, 135, 134, 133, 132, 132, 131, ...      3
33  [137, 136, 135, 135, 134, 133, 132, 132, 131, ...      3
34  [146, 143, 140, 139, 137, 132, 128, 125, 120, ...      3
35  [68, 66, 60, 56, 53, 51, 50, 51, 47, 48, 48, 4...      3
36  [68, 66, 60, 56, 53, 51, 50, 51, 47, 48, 48, 4...      3
37  [68, 66, 60, 56, 53, 51, 50, 51, 47, 48, 48, 4...      3
38  [53, 51, 49, 48, 48, 48, 47, 46, 45, 46, 43, 4...      3
39  [53, 51, 49, 48, 48, 48, 47, 46, 45, 46, 43, 4...      3
40  [53, 51, 49, 48, 48, 48, 47, 46, 45, 46, 43, 4...      3
41  [51, 52, 49, 47, 46, 44, 45, 44, 43, 43, 44, 4...      3
42  [80, 80, 80, 79, 78, 77, 76, 76, 76, 76, 75, 7...      3
43  [80, 80, 80, 79, 78, 77, 76, 76, 76, 76, 75, 7...      3
44  [80, 80, 80, 79, 78, 77, 76, 76, 76, 76, 75, 7...      3

In [17]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\4")
img4=[]
for i in os.listdir():
    img4.append(cv2.imread(r"C:\Users\SSS\Desktop\opencv_task\4\{}".format(i),0).flatten())
    data_four=pd.DataFrame({'array':img4,'label':4})
img4

[array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 194, ...,   1,   1,   1], dtype=uint8),
 array([197, 196, 194, ...,   1,   1,   1], dtype=uint8),
 array([197, 196, 194, ...,   1,   1,   1], dtype=uint8),
 array([193, 194, 194, ...,   0,   0,   0], dtype=uint8),
 array([193, 194, 194, ...,   0,   0,   0], dtype=uint8),
 array([193, 194, 194, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 195, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 195, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 195, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 194, ...,   2,   1,   1], dtype=uint8),
 array([197, 196, 194, ...,   2,   1,   1], dtype=uint8),
 array([197, 196, 194, ...,   2,   1,   1], dtype=uint8),
 array([193, 193, 193, ...,   0,   0,   0], dtype=uint8),
 array([193, 193, 193, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 197, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 197, ...,   0,   0,   0], dtype=uint8),
 array([198, 198, 197, ...,   0,   0,   0], dtype=uint8),
 array([198, 198, 197, ...,   0,   0,   0], dtype=uint8),
 array([198, 198, 197, ...,   0,   0,   0], dtype=uint8),
 array([195, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([195, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([195, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([198, 196, 193, ...,   0,   0,   1], dtype=uint8),
 array([198, 196, 193, ...,   0,   0,   1], dtype=uint8),
 array([198, 196, 193, ...,   0,   0,   1], dtype=uint8),
 array([196, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([196, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([196, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([198, 196, 193, ...,   0,   0,   0], dtype=uint8),
 array([198, 196, 193, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   1], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   1], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   1], dtype=uint8),
 array([197, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([190, 189, 187, ...,   0,   0,   0], dtype=uint8),
 array([192, 190, 187, ...,   1,   1,   1], dtype=uint8),
 array([192, 190, 187, ...,   1,   1,   1], dtype=uint8),
 array([192, 190, 187, ...,   1,   1,   1], dtype=uint8),
 array([195, 193, 190, ...,   1,   0,   0], dtype=uint8),
 array([195, 193, 190, ...,   1,   0,   0], dtype=uint8),
 array([193, 192, 191, ...,   0,   0,   0], dtype=uint8),
 array([193, 192, 191, ...,   0,   0,   0], dtype=uint8),
 array([193, 192, 191, ...,   0,   0,   0], dtype=uint8),
 array([193, 193, 191, ...,   0,   0,   0], dtype=uint8),
 array([193, 193, 191, ...,   0,   0,   0], dtype=uint8),
 array([193, 193, 191, ...,   0,   0,   0], dtype=uint8),
 array([195, 196, 196, ...,   0,   0,   0], dtype=uint8),
 array([195, 196, 196, ...,   0,   0,   0], dtype=uint8),
 array([195, 196, 196, ...,   0,   0,   0], dtype=uint8),
 array([201, 201, 199, ...,   1,   1,   1], dtype=uint8),
 array([201, 201, 199, ...,   1,   1,   1], dtype=uint8),
 array([201, 201, 199, ...,   1,   1,   1], dtype=uint8),
 array([197, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([200, 198, 196, ...,   1,   1,   1], dtype=uint8),
 array([200, 198, 196, ...,   1,   1,   1], dtype=uint8),
 array([200, 198, 196, ...,   1,   1,   1], dtype=uint8),
 array([196, 196, 194, ...,   1,   1,   1], dtype=uint8),
 array([196, 196, 194, ...,   1,   1,   1], dtype=uint8),
 array([196, 196, 194, ...,   1,   1,   1], dtype=uint8),
 array([198, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([198, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([198, 196, 194, ...,   0,   0,   0], dtype=uint8),
 array([200, 199, 198, ...,   0,   1,   1], dtype=uint8),
 array([200, 199, 198, ...,   0,   1,   1], dtype=uint8),
 array([200, 199, 198, ...,   0,   1,   1], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([194, 194, 194, ...,   1,   1,   1], dtype=uint8),
 array([194, 194, 194, ...,   1,   1,   1], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([195, 195, 194, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([197, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 196, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 196, ...,   0,   0,   0], dtype=uint8),
 array([197, 197, 196, ...,   0,   0,   0], dtype=uint8),
 array([195, 195, 193, ...,   1,   0,   0], dtype=uint8),
 array([195, 195, 193, ...,   1,   0,   0], dtype=uint8),
 array([195, 195, 193, ...,   1,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8),
 array([196, 196, 195, ...,   0,   0,   0], dtype=uint8)]

In [18]:
data_four

                                                array  label
0   [196, 196, 195, 194, 193, 191, 189, 186, 185, ...      4
1   [197, 196, 194, 193, 192, 191, 189, 188, 186, ...      4
2   [197, 196, 194, 193, 192, 191, 189, 188, 186, ...      4
3   [197, 196, 194, 193, 192, 191, 189, 188, 186, ...      4
4   [193, 194, 194, 193, 192, 190, 188, 186, 184, ...      4
..                                                ...    ...
93  [195, 195, 193, 192, 190, 190, 188, 187, 185, ...      4
94  [195, 195, 193, 192, 190, 190, 188, 187, 185, ...      4
95  [195, 195, 193, 192, 190, 190, 188, 187, 185, ...      4
96  [196, 196, 195, 194, 193, 191, 189, 186, 185, ...      4
97  [196, 196, 195, 194, 193, 191, 189, 186, 185, ...      4

[98 rows x 2 columns]

In [20]:
os.chdir(r"C:\Users\SSS\Desktop\opencv_task\5")
img5=[]
for i in os.listdir():
    img5.append(cv2.imread(r"C:\Users\SSS\Desktop\opencv_task\5\{}".format(i),0).flatten())
    data_five=pd.DataFrame({'array':img5,'label':5})
img5

[array([157, 154, 151, ...,   0,   0,   0], dtype=uint8),
 array([157, 154, 151, ...,   0,   0,   0], dtype=uint8),
 array([159, 157, 153, ...,   0,   0,   0], dtype=uint8),
 array([159, 157, 153, ...,   0,   0,   0], dtype=uint8),
 array([159, 157, 153, ...,   0,   0,   0], dtype=uint8),
 array([161, 160, 158, ...,   0,   0,   0], dtype=uint8),
 array([161, 160, 158, ...,   0,   0,   0], dtype=uint8),
 array([161, 160, 158, ...,   0,   0,   0], dtype=uint8),
 array([162, 160, 158, ...,   0,   0,   0], dtype=uint8),
 array([162, 160, 158, ...,   0,   0,   0], dtype=uint8),
 array([163, 160, 159, ...,   0,   0,   0], dtype=uint8),
 array([163, 160, 159, ...,   0,   0,   0], dtype=uint8),
 array([163, 160, 159, ...,   0,   0,   0], dtype=uint8),
 array([166, 168, 162, ...,   0,   0,   0], dtype=uint8),
 array([166, 168, 162, ...,   0,   0,   0], dtype=uint8),
 array([166, 168, 162, ...,   0,   0,   0], dtype=uint8),
 array([164, 163, 161, ...,   0,   0,   0], dtype=uint8),
 array([164, 163, 161, ...,   0,   0,   0], dtype=uint8),
 array([164, 163, 161, ...,   0,   0,   0], dtype=uint8),
 array([168, 166, 165, ...,   0,   0,   0], dtype=uint8),
 array([168, 166, 165, ...,   0,   0,   0], dtype=uint8),
 array([168, 166, 165, ...,   0,   0,   0], dtype=uint8),
 array([168, 168, 167, ...,   0,   0,   0], dtype=uint8),
 array([168, 168, 167, ...,   0,   0,   0], dtype=uint8),
 array([168, 168, 167, ...,   0,   0,   0], dtype=uint8),
 array([172, 170, 167, ...,   0,   0,   0], dtype=uint8),
 array([172, 170, 167, ...,   0,   0,   0], dtype=uint8),
 array([172, 170, 167, ...,   0,   0,   0], dtype=uint8),
 array([172, 171, 168, ...,   0,   0,   0], dtype=uint8),
 array([172, 170, 168, ...,   0,   0,   0], dtype=uint8),
 array([172, 170, 168, ...,   0,   0,   0], dtype=uint8),
 array([175, 174, 173, ...,   0,   0,   0], dtype=uint8),
 array([175, 174, 173, ...,   0,   0,   0], dtype=uint8),
 array([175, 174, 173, ...,   0,   0,   0], dtype=uint8),
 array([176, 175, 173, ...,   0,   0,   0], dtype=uint8),
 array([176, 175, 173, ...,   0,   0,   0], dtype=uint8),
 array([176, 175, 173, ...,   0,   0,   0], dtype=uint8),
 array([178, 177, 176, ...,   0,   0,   0], dtype=uint8),
 array([178, 177, 176, ...,   0,   0,   0], dtype=uint8),
 array([178, 177, 176, ...,   0,   0,   0], dtype=uint8),
 array([180, 178, 176, ...,   0,   0,   0], dtype=uint8),
 array([180, 178, 176, ...,   0,   0,   0], dtype=uint8),
 array([180, 178, 176, ...,   0,   0,   0], dtype=uint8),
 array([183, 183, 182, ...,   0,   0,   0], dtype=uint8),
 array([183, 183, 182, ...,   0,   0,   0], dtype=uint8),
 array([181, 179, 177, ...,   0,   0,   0], dtype=uint8),
 array([181, 179, 177, ...,   0,   0,   0], dtype=uint8),
 array([181, 179, 177, ...,   0,   0,   0], dtype=uint8),
 array([185, 184, 182, ...,   0,   0,   0], dtype=uint8),
 array([185, 184, 182, ...,   0,   0,   0], dtype=uint8),
 array([185, 184, 182, ...,   0,   0,   0], dtype=uint8),
 array([187, 185, 183, ...,   0,   0,   0], dtype=uint8),
 array([187, 185, 183, ...,   0,   0,   0], dtype=uint8),
 array([187, 185, 183, ...,   0,   0,   0], dtype=uint8),
 array([189, 188, 185, ...,   0,   0,   0], dtype=uint8)]

In [21]:
data_five

                                                array  label
0   [157, 154, 151, 150, 150, 149, 147, 146, 142, ...      5
1   [157, 154, 151, 150, 150, 149, 147, 146, 142, ...      5
2   [159, 157, 153, 151, 150, 148, 147, 145, 149, ...      5
3   [159, 157, 153, 151, 150, 148, 147, 145, 149, ...      5
4   [159, 157, 153, 151, 150, 148, 147, 145, 149, ...      5
5   [161, 160, 158, 156, 154, 152, 149, 146, 144, ...      5
6   [161, 160, 158, 156, 154, 152, 149, 146, 144, ...      5
7   [161, 160, 158, 156, 154, 152, 149, 146, 144, ...      5
8   [162, 160, 158, 157, 157, 156, 156, 156, 156, ...      5
9   [162, 160, 158, 157, 157, 156, 156, 156, 156, ...      5
10  [163, 160, 159, 159, 158, 156, 155, 156, 150, ...      5
11  [163, 160, 159, 159, 158, 156, 155, 156, 150, ...      5
12  [163, 160, 159, 159, 158, 156, 155, 156, 150, ...      5
13  [166, 168, 162, 164, 160, 159, 156, 154, 152, ...      5
14  [166, 168, 162, 164, 160, 159, 156, 154, 152, ...      5
15  [166, 168, 162, 164, 160, 159, 156, 154, 152, ...      5
16  [164, 163, 161, 158, 156, 155, 154, 153, 151, ...      5
17  [164, 163, 161, 158, 156, 155, 154, 153, 151, ...      5
18  [164, 163, 161, 158, 156, 155, 154, 153, 151, ...      5
19  [168, 166, 165, 166, 165, 162, 159, 157, 157, ...      5
20  [168, 166, 165, 166, 165, 162, 159, 157, 157, ...      5
21  [168, 166, 165, 166, 165, 162, 159, 157, 157, ...      5
22  [168, 168, 167, 165, 162, 159, 157, 155, 153, ...      5
23  [168, 168, 167, 165, 162, 159, 157, 155, 153, ...      5
24  [168, 168, 167, 165, 162, 159, 157, 155, 153, ...      5
25  [172, 170, 167, 165, 165, 164, 163, 162, 158, ...      5
26  [172, 170, 167, 165, 165, 164, 163, 162, 158, ...      5
27  [172, 170, 167, 165, 165, 164, 163, 162, 158, ...      5
28  [172, 171, 168, 166, 164, 163, 162, 161, 158, ...      5
29  [172, 170, 168, 165, 164, 163, 162, 160, 159, ...      5
30  [172, 170, 168, 165, 164, 163, 162, 160, 159, ...      5
31  [175, 174, 173, 171, 169, 168, 168, 168, 168, ...      5
32  [175, 174, 173, 171, 169, 168, 168, 168, 168, ...      5
33  [175, 174, 173, 171, 169, 168, 168, 168, 168, ...      5
34  [176, 175, 173, 172, 171, 170, 168, 167, 165, ...      5
35  [176, 175, 173, 172, 171, 170, 168, 167, 165, ...      5
36  [176, 175, 173, 172, 171, 170, 168, 167, 165, ...      5
37  [178, 177, 176, 174, 172, 170, 169, 168, 168, ...      5
38  [178, 177, 176, 174, 172, 170, 169, 168, 168, ...      5
39  [178, 177, 176, 174, 172, 170, 169, 168, 168, ...      5
40  [180, 178, 176, 175, 175, 174, 173, 170, 170, ...      5
41  [180, 178, 176, 175, 175, 174, 173, 170, 170, ...      5
42  [180, 178, 176, 175, 175, 174, 173, 170, 170, ...      5
43  [183, 183, 182, 180, 178, 176, 176, 176, 173, ...      5
44  [183, 183, 182, 180, 178, 176, 176, 176, 173, ...      5
45  [181, 179, 177, 175, 173, 171, 170, 169, 170, ...      5
46  [181, 179, 177, 175, 173, 171, 170, 169, 170, ...      5
47  [181, 179, 177, 175, 173, 171, 170, 169, 170, ...      5
48  [185, 184, 182, 180, 179, 178, 176, 175, 175, ...      5
49  [185, 184, 182, 180, 179, 178, 176, 175, 175, ...      5
50  [185, 184, 182, 180, 179, 178, 176, 175, 175, ...      5
51  [187, 185, 183, 181, 180, 179, 177, 176, 173, ...      5
52  [187, 185, 183, 181, 180, 179, 177, 176, 173, ...      5
53  [187, 185, 183, 181, 180, 179, 177, 176, 173, ...      5
54  [189, 188, 185, 182, 180, 179, 179, 179, 177, ...      5

created array and label for one finger sign,two finger sign,three finger sign,four finger sign,five finger sign with label 1,2,3,4,5 for grey scale image converted to vector